MAINT-7812: Add /marker switch when executing NSIS installer.
Refactor launch_as_child() and launch_as_replacement() functions into
PopenRunner and ExecRunner, classes whose run() methods perform the equivalent
operations. This lets low-level code indicate to its caller which operation is
intended.

Pass the intended command line, with the original viewer binary plus any
command-line args, into update_manager() and from there into install() and
apply_update(). This lets apply_update(), install() and update_manager()
return one of the aforementioned Runner subclasses with all applicable
arguments. That means that SL_Launcher doesn't need to decide whether to call
launch_as_child() or launch_as_replacement(): it simply calls run() on the
returned Runner object.

Move the decision about whether to pass '--set SkipBenchmark 1' on Windows 10
into update_manager(), instead of in the guts of launch_as_child() (or
PopenRunner.run()). The code that finally calls Popen() isn't supposed to know
that much about what process it's running, or what command-line arguments it
will accept.

Make apply_mac_update() provide the /usr/bin/open command, instead of deciding
that in the guts of launch_as_replacement() (or ExecRunner.run()).

Remove apply_mac_update()'s temp mount point directory on exit. Seems I've
been accumulating a lot of empty temp directories recently.

Eliminate use of uninitialized ArgumentParser().parse_known_args(), returning
an empty Namespace object (which is discarded) along with a list identical to
sys.argv[1:]. Use of parse_known_args() when no args are known has confused me
every single time I've looked at this code. Use sys.argv[1:] instead. This
fixes a bug in the version < 2.7 stanza, when argparse is referenced before
being imported.

The (never-tested) apply_linux_update() function is never passed in_place any
longer. Just eliminate the in_place parameter and the test on it. Also fix
undefined reference to lowercase install_dir.