MAINT-8304: Guess possible fix for mysterious EC2 TeamCity failure.
The current build-cmd.py works fine on my Windows 7 development box, but
the nosetests run produces errors of the form:

ImportError: DLL load failed: %1 is not a valid Win32 application.

(one of my favorite Windows unhelpful error messages)
on the TeamCity EC2 instance we use for Windows builds.

Since this possibly has something to do with finding the wrong version(s) of
something(s), try NOT overriding PYTHON_PATH in environment passed to
nosetests.